spring.application.name=banking-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app
spring.datasource.username=[PostgreSQL Username]
spring.datasource.password=[PostgreSQL Password]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=replace_with_a_long_random_base64_string
jwt.expiration=86400000

server.port=8080
